apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup-cronjob
  namespace: quorum
spec:
  schedule: "*/5 * * * *"  # Schedule to run every 5 minutes
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backup
            image: otariexplorins/my-backup-image
            env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: aws_access_key_id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: aws_secret_access_key
            - name: AWS_DEFAULT_REGION
              value: "eu-central-1"
          restartPolicy: OnFailure