apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-access-rolebinding
  namespace: quorum
subjects:
- kind: ServiceAccount
  name: pod-access-sa
  namespace: quorum
roleRef:
  kind: Role
  name: pod-access-role
  apiGroup: rbac.authorization.k8s.io