apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-access-role
  namespace: quorum
rules:
- apiGroups: [""]
  resources: ["pods", "pods/exec"]
  verbs: ["get", "list", "create"]