---
image:
  blockscout:
    repository: consensys/blockscout
    tag: v4.0.0-beta
    pullPolicy: IfNotPresent

postgresql:
  postgresqlDatabase: postgres
  postgresqlUsername: postgres
  postgresqlPassword: postgres
  initdbUser: postgres
  initdbPassword: postgres
  enabled: true

blockscout:
  # cpu dependent
  resources:
    cpuLimit: 0.7
    cpuRequest: 0.5
    memLimit: "2G"
    memRequest: "1G"
  port: 4000
  # port: 5432
  database_url: "ecto://postgres:postgres@blockscout-postgresql/postgres?ssl=false"
  # database_url: "besu-postgres.ctwgr32c2ir3.eu-west-1.rds.amazonaws.com"
  postgres_password: postgres
  postgres_user: postgres
  network: quorum
  subnetwork: consensys
  chain_id: 39123
  coin: eth
  ethereum_jsonrpc_variant: besu
  ethereum_jsonrpc_transport: http
  ethereum_jsonrpc_endpoint: "besu-node-bootnode-2" # service name to be used
  secret_key_base: "VTIB3uHDNbvrY0+60ZWgUoUBKDn9ppLR8MI4CpRz4/qLyEFs54ktJfaNT6Z221" # change me please
