---
# ingress-nginx IngressClass
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: network-nginx
  namespace: quorum
spec:
  controller: k8s.io/network-ingress-nginx

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: besu-ingress-routes
  namespace: quorum
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
    # nginx.ingress.kubernetes.io/configuration-snippet: |
    #   rewrite (?i)/tessera-[0-9]?/(.*) /$1 break;
    #   rewrite (?i)/tessera-[0-9]?$ / break;    
    #   rewrite (?i)/kibana/(.*) /$1 break;
    #   rewrite (?i)/kibana$ / break;
    nginx.ingress.kubernetes.io/rewrite-target: /
    #nginx.ingress.kubernetes.io/whitelist-source-range: w.x.y.z/32,a.b.c.d/32
    # restrict access to cluster only from PERS dns
    # nginx.ingress.kubernetes.io/server-alias: "pers.ninja, api.pers.ninja, dev.api.pers.ninja"
    nginx.ingress.kubernetes.io/limit-connections: "10"
    nginx.ingress.kubernetes.io/limit-rps: "10"

    # nginx.ingress.kubernetes.io/auth-type: jwt
    # nginx.ingress.kubernetes.io/auth-secret: jwt-secret
    # nginx.ingress.kubernetes.io/auth-realm: "Authentication Required"
    # nginx.ingress.kubernetes.io/auth-token-signing-key: '-----BEGIN PUBLIC KEY-----
    #                                                       MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmsn7vjTOrbQguwmGhXLd
    #                                                       1JL0rJCk3hBjU9RVwUQetsWslLEQ9zioIR2O9PIiuhMgHigaix/Y5Y/Trida/mvP
    #                                                       LPPhio1EcQoL73kdaP4yMRVmKY0kKnxO0tfOE4Oellrk82KqHvRdZjY71Gy2I2ke
    #                                                       rwx3qY+7q7FgPRlz71WjO/lPXXrs7ZZtGrjvttRq9jnS9s2SkSjIQPnvPKDHJdci
    #                                                       4aMWvVPheNRa/+1WIXgYuzmO3er1PMeuPBmyFgqgVLD7nv2inpM1Scaceh6xIlvq
    #                                                       naX0svhefmdUI0N4WoUkwT1ZFmHv1Col9MvXElDZeNaD/VHha7mvq/JkqU4lJ7Cq
    #                                                       4QIDAQAB
    #                                                       -----END PUBLIC KEY-----'
    # rpc-http-authentication-enabled: "true"
    # rpc-http-authentication-jwt-public-key-file: "/gasagebi/publicRSAKey.pem"


spec:
  ingressClassName: network-nginx
  rules:
  - http:
      paths:
      - path: /rpc
        pathType: Prefix
        backend:
          service:
            name: besu-node-rpc-1
            port:
              number: 8545
      - path: /validator-1
        pathType: Prefix
        backend:
          service:
            name: besu-node-validator-1
            port:
              number: 8545
      - path: /validator-2
        pathType: Prefix
        backend:
          service:
            name: besu-node-validator-2
            port:
              number: 8545
      - path: /validator-3
        pathType: Prefix
        backend:
          service:
            name: besu-node-validator-3
            port:
              number: 8545
      - path: /validator-4
        pathType: Prefix
        backend:
          service:
            name: besu-node-validator-4
            port:
              number: 8545
      - path: /member-1
        pathType: Prefix
        backend:
          service:
            name: besu-node-member-1
            port:
              number: 8545
      - path: /tessera-1
        pathType: Prefix
        backend:
          service:
            name: besu-node-member-1
            port:
              number: 9080
      - path: /member-2
        pathType: Prefix
        backend:
          service:
            name: besu-node-member-2
            port:
              number: 8545
      - path: /tessera-2
        pathType: Prefix
        backend:
          service:
            name: besu-node-member-2
            port:
              number: 9080
      - path: /member-3
        pathType: Prefix
        backend:
          service:
            name: besu-node-member-3
            port:
              number: 8545
      - path: /tessera-3
        pathType: Prefix
        backend:
          service:
            name: besu-node-member-3
            port:
              number: 9080
      - path: /kibana
        pathType: Prefix
        backend:
          service:
            name: kibana-kibana
            port:
              number: 5601
      - path: /
        pathType: Prefix
        backend:
          service:
            name: monitoring-grafana
            port:
              number: 3000
